# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='car_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=400)),
                ('from_id', models.CharField(max_length=400)),
                ('to', models.CharField(max_length=400)),
            ],
        ),
    ]
